### ISSUE TITLE
# OAuth2 기반 소셜 로그인 모듈 

### ISSUE THREAD

**Issue by RookieAND** [TEO-SPRINT-14th-9team/mz2mo-client#1]
## 📚 Epic
OAuth2 기반 소셜 로그인 모듈 

## 🗂 Desc

- OAuth2 기반의 소셜 로그인 관련 모듈을 제작합니다.
- 각 소셜 플랫폼에서 제공하는 access code를 받는 redirect Page를 제작합니다.

## 🔍 Work

- [x]  소셜 로그인 관련 API 제작
- [x]  소셜 플랫폼에서 제공하는 Access Code를 인계하는 Page 생성
- [x]  백엔드로부터 인계 받은 Code를 전송하는 API Mock 제작
