### ISSUE TITLE
# Spotify SDK 와 관련된 Custom Hook 연동

### ISSUE THREAD

**Issue by RookieAND** [TEO-SPRINT-14th-9team/mz2mo-client#13]
## 📚 Epic
Spotify SDK 와 관련된 Custom Hook 연동

## 🗂 Desc

- Spotify SDK 와 @haryung-lee (하랭) 이 제작한 Custom Hook을 연동합니다.
- 관련 SDK 작업을 @C12H22O12 (꾺) 이 제작한 플레이어 바와 연동합니다.
- 재생 목록 관련 작업도 추가적으로 진행하여 곡을 연속적으로 듣도록 합니다.

## 🔍 Work

- [x]  Spotify SDK와 관련한 Custom Hook 연동
- [x]  플레이어 바와 Spotify SDK 간의 연동
- [x]  재생 목록 관련 작업도 추가적으로 진행
