### ISSUE TITLE
# 스플래시 페이지 스타일 제작

### ISSUE THREAD

**Issue by Changsoon-Yun** [TEO-SPRINT-14th-9team/mz2mo-client#14]
## 📚 Epic
스플래시 페이지 스타일 제작

## 🗂 Desc

- 스플래시 페이지 - 장르 선택 화면 스타일 제작
- 스플래시 페이지 - 공감 화면 스타일 제작
- 스플래시 페이지 - 둘러보기 스타일 제작

## 🔍 Work

- [x]  스플래시 페이지 - 장르 선택 화면
- [x]  스플래시 페이지 - 공감 화면
- [x]  스플래시 페이지 - 둘러보기
