### ISSUE TITLE
# 뮤직 플레이어 바 UI 적용

### ISSUE THREAD

**Issue by RookieAND** [TEO-SPRINT-14th-9team/mz2mo-client#22]
## 📚 Epic
# 뮤직 플레이어 바 UI 적용

## 🗂 Desc

- 뮤직 플레이어 바 UI를 적용합니다.
- 비로그인 시 뮤직 플레이어 바를 비활성화 하도록 합니다.
- 곡 재생, 멈춤, 프로그레시브 바, 반복 관련 모드 설정을 적용합니다.
- 

## 🔍 Work

- [x]  Figma 내의 뮤직 플레이어 바 UI 적용
- [x]  재생, 멈춤, 반복 관련 버튼 추가 및 기능 연동
- [ ]  프로그레시브 바, 음량 조절 버튼 추가 및 기능 연동
- [x] 곡명, 가수 이름 디스플레이 적용 (애니메이션 적용은 추후에)
