### ISSUE TITLE
스플래시 페이지 API 연동 및 스타일 수정

### ISSUE THREAD

**Issue by Changsoon-Yun** [TEO-SPRINT-14th-9team/mz2mo-client#29]
📚 Epic
스플래시 페이지 API 연동 및 스타일 수정

🗂 Desc
스플래시 페이지
styled-compoent className 에러

🔍 Work
- [ ] 스플래시 페이지 - 장르 선택 화면
- [ ] 스플래시 페이지 - 공감 화면
- [ ] 스플래시 페이지 - 둘러보기
- [x] styled-component 에러 - [링크](https://tesseractjh.tistory.com/164)
